# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: check change tags

on:
  pull_request:
    paths:
      - '.changes/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changes:
              - added|modified: '.changes/*.md'

      - name: check
        run: node ./.scripts/ci/check-change-tags.js ${{ steps.filter.outputs.changes_files }}
        if: ${{ steps.filter.outputs.changes == 'true' }}
